// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpi93PMMbFkTtS2SzDP0v65VsKRrMaKo',
    appId: '1:389035325087:web:6f21c178628ac5681814aa',
    messagingSenderId: '389035325087',
    projectId: 'fluttertut-5edca',
    authDomain: 'fluttertut-5edca.firebaseapp.com',
    storageBucket: 'fluttertut-5edca.appspot.com',
    measurementId: 'G-2G4HLHX1HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrI3OgdsPIU_rlZFXqB6JdBDvZ24LXOY0',
    appId: '1:389035325087:android:ae2eabef0e313d2b1814aa',
    messagingSenderId: '389035325087',
    projectId: 'fluttertut-5edca',
    storageBucket: 'fluttertut-5edca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBwLAXqRfrjmmyl5-hPKUwogu9AkFdkVs',
    appId: '1:389035325087:ios:b0886965f2dbabde1814aa',
    messagingSenderId: '389035325087',
    projectId: 'fluttertut-5edca',
    storageBucket: 'fluttertut-5edca.appspot.com',
    iosClientId: '389035325087-o0n5b4fftgml9rif2nans732drm7e9g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBwLAXqRfrjmmyl5-hPKUwogu9AkFdkVs',
    appId: '1:389035325087:ios:b0886965f2dbabde1814aa',
    messagingSenderId: '389035325087',
    projectId: 'fluttertut-5edca',
    storageBucket: 'fluttertut-5edca.appspot.com',
    iosClientId: '389035325087-o0n5b4fftgml9rif2nans732drm7e9g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
